# Site configuration

site_name: RetroDECK Wiki
site_description: The Official RetroDECK Wiki

# Copyright
copyright: "&copy; 2023 RetroDECK Team"

# Theme Configuration
theme:
  name: "material"
  language: "en"
  logo: wiki_icons/retrodeck/rd_icon_circle_32x32.png
  features:
   - navigation.prune
   - navigation.path
   - navigation.sections
  palette:
    scheme: slate
    primary: "deep purple"
    accent: "white"
plugins:
   - search:
   - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
   - blog:
       enabled: true
       post_url_date_format: yyyy/MM/dd
       post_date_format: full
       blog_toc: true
       archive: true
       archive_date_format: yyyy
       pagination: false
       pagination: false
       post_excerpt: required
       post_excerpt_separator: <!-- more -->

# Sidebar Navigation

nav:
  - Wiki Home 🏠: index.md
  - Blog: blog/index.md
  - General Information 📰:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Devices: wiki_general/supported-devices.md
    - RetroDECK - Steam Input Controllers (WIP): wiki_general/retrodeck-input-support.md
    - The RetroDECK Beta: wiki_general/beta-period.md
    - The FAQ ❔:  wiki_general/faq.md
    - Start using RetroDECK: wiki_general/retrodeck-start.md

  - About RetroDECK 📖:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Easter Egg - Boot Logos: wiki_about/boot-logos.md
    - Donations & Licenses 🎁: wiki_about/donations-licenses.md

  - Community & Helping Out ❤️:
    - Discord: wiki_community/discord.md
    - Lemmy/Reddit: wiki_community/lemmy-reddit.md
    - How to Contribute to RetroDECK?: wiki_community/contibute-rd.md

  - Bugs & Issues 🐜:
    - Reporting Bugs: wiki_bugs/report-bugs.md
    - Known Issues: wiki_bugs/known-issues.md
    - How do I help out with testing?: wiki_community/testing-rd.md

  - Development 🧪:
    - Current Version: wiki_rd_versions/version_0.7b/0.7.5b.md
    - Version History (Patchnotes): wiki_rd_versions/version-history.md
    - What are you working on?: wiki_development/what-are-you-working.on.md
    - Folders and Filepaths: wiki_development/folders-filepaths.md
    - CLI Guide: wiki_development/cli-guide.md
    - Development Notes: wiki_development/general-development.md

  - RetroDECK Configurator 🛠️:
    - Configurator Features: wiki_general/configurator.md

  - RetroDECK Management 🗜️:
    - Manage your Games: wiki_management/games-management.md
    - Manage your BIOS/Firmware: wiki_management/bios-firmware.md
    - Move RetroDECK to a new device: wiki_management/retrodeck-move.md

  - RetroDECK and Steam 💻:
    - Add RetroDECK to Steam: wiki_steam/add-to-steam.md
    - Enable Controllers in Steam: wiki_steam//enable-controllers-steam.md
    - Change controller order in Steam: wiki_steam//set-controller-order-steam.md
    - RetroDECK and Steam Input: wiki_steam/steam-input.md

  - Steam Deck 🕹️:
    - Steam Deck - RetroDECK Installation and Updates: wiki_devices/steamdeck/steamdeck-start.md
    - Steam Deck - Optimizations: wiki_devices/steamdeck/steamdeck-optimize.md
    - Steam Deck - Recommended Software: wiki_devices/steamdeck/steamdeck-software.md
    - Steam Deck - Controls: wiki_controllers/steam/controllers-steamdeck.md

  - Linux Desktop 🐧:
    - Linux Desktop - Installation and Updates: wiki_devices/linux_desktop/linux-install.md
    - Linux Desktop - Recommended Software: wiki_devices/linux_desktop/linux-software.md

  - EmulationStation-DE Guide 📘:
    - ES-DE User Guide: wiki_emulationStation_de/esde-guide.md
    - ES-DE Themes: wiki_emulationStation_de/esde-themes.md
    - ES-DE Folders and Files (WIP): wiki_emulationStation_de/esde-folders-files.md

  - Guide - GZDoom (WIP):
    - GZDoom Guide 📙: wiki_emulator_guides/gzdoom/gzdoom-guide.md
    - Get the WADs from bought DOOM / DOOM 2 (WIP): wiki_emulator_guides/gzdoom/extract-doom-wads.md

  - Emulator Guides 📙 (WIP):
    - RPCS3: wiki_emulator_guides/rpcs3-guide.md
    - Yuzu: wiki_emulator_guides/yuzu-guide.md
    - ScummVM: wiki_emulator_guides/scummvm-guide.md
    - Cemu (WIP): wiki_emulator_guides/cemu-guide.md
    - Citra (WIP): wiki_emulator_guides/citra-guide.md
    - Dolphin / Primehack (WIP): wiki_emulator_guides/dolphin-primehack-guide.md
    - Duckstation (WIP): wiki_emulator_guides/duckstation-guide.md
    - IkemenGO - M.U.G.E.N (WIP): wiki_emulator_guides/ikemengo-guide.md
    - MAME (WIP): wiki_emulator_guides/mame-guide.md
    - MelonDS (WIP): wiki_emulator_guides/melonds-guide.md
    - OpenBOR (WIP): wiki_emulator_guides/openbor-guide.md
    - PCSX2 (WIP): wiki_emulator_guides/pcsx2-guide.md
    - PICO-8 (WIP): wiki_emulator_guides/pico8-guide.md
    - PPSSPP (WIP): wiki_emulator_guides/ppsspp-guide.md
    - RetroArch (WIP): wiki_emulator_guides/retroarch-guide.md
    - Ryujinx (WIP): wiki_emulator_guides/ryujinx-guide.md
    - Solarus (WIP): wiki_emulator_guides/solarus-guide.md
    - Vita3K: wiki_emulator_guides/vita3k-guide.md
    - Xemu (WIP): wiki_emulator_guides/xemu-guide.md

  - Mod Guides ⚙️:
    - Mods - Citra: wiki_mods/citra-mods.md
    - Mods - Dolphin/Primehack: wiki_mods/dolphin-prime-mods.md
    - Mods - Ryujinx (WIP): wiki_mods/ryujinx-mods.md
    - Mods - Yuzu: wiki_mods/yuzu-mods.md

  - Texture Pack Guides 🖌️:
    - Texture Packs - Citra: wiki_texture_packs/citra-tp.md
    - Texture Packs - Dolphin/Primehack: wiki_texture_packs/dolphing-prime-tp.md
    - Texture Packs - Duckstation: wiki_texture_packs/duckstation-tp.md
    - Texture Packs - PCSX2: wiki_texture_packs/pcsx2-tp.md
    - Texture Packs - PPSSPP: wiki_texture_packs/ppsspp-tp.md
    - Texture Packs - RetroArch Mesen: wiki_texture_packs/retroarch-mesen-tp.md
    - Texture Packs - RetroArch Mupen64Plus: wiki_texture_packs/retroarch-mupen64plus-tp.md

  - About Controllers 🎮:
    - Different Button Prompts in Games: wiki_controllers/about/diffrent-game-inputs.md
    - RetroDECK with Steam Input: wiki_controllers/about/about-steam-input.md
    - RetroDECK and Udev Rules: wiki_controllers/about/about-udev.md
    - RetroDECK and Steam Input: wiki_steam/steam-input.md

  - Controllers - Nintendo (WIP):
    - Nintendo - RetroDECK Hotkeys: wiki_controllers/nintendo/nintendo-hotkeys.md
    - Switch - Pro Controller: wiki_controllers/nintendo/switch-pro.md
    - Switch - Joy-Cons: wiki_controllers/nintendo/joycon.md
    - Switch - Ring Fit: wiki_controllers/nintendo/ring-fit.md
    - Wii U - Gamepad: wiki_controllers/nintendo/wiiu-gamepad.md
    - Wii - Wii Remote (Wiimote): wiki_controllers/nintendo/wii-remote.md
    - Wii - Wii Balance Board: wiki_controllers/nintendo/wii-balance-board.md
    - Gamecube - PC / WiiU Adapter: wiki_controllers/nintendo/gamecube-adapter.md

  - Controllers - Playstation (WIP):
    - Playstation - RetroDECK Hotkeys: wiki_controllers/playstation/playstation-hotkeys.md
    - Playstation 2 - EyeToy: wiki_controllers/playstation/eyetoy.md
    - Playstation 3 - DualShock 3: wiki_controllers/playstation/dualshock-3.md
    - Playstation 3 - Eye & Move: wiki_controllers/playstation/playstation-move.md
    - Playstation 4 - DualShock 4: wiki_controllers/playstation/dualshock-4.md
    - Playstation 5 - DualSense: wiki_controllers/playstation/dualsense.md
    - Playstation 5 - DualSense Edge: wiki_controllers/playstation/dualsense-edge.md

  - Controllers - Xbox (WIP):
    - Xbox - RetroDECK Hotkeys: wiki_controllers/xbox/xbox-hotkeys.md
    - Xbox 360 - Controller: wiki_controllers/xbox/xbox-360.md
    - Xbox 360 - Kinect V1: wiki_controllers/xbox/xbox-360-kinect.md
    - Xbox One - Kinect V2: wiki_controllers/xbox/xbox-one-kinect.md
    - Xbox One/S/X - Xbox Wireless Controller: wiki_controllers/xbox/xbox-wireless.md
    - Xbox S/X - Xbox Elite Series 2: wiki_controllers/xbox/xbox-wireless-elite.md
    - Xbox Adaptive Controller: wiki_controllers/accessibility/xac.md

  - Controllers - Steam/Valve (WIP):
    - Steam Deck - Controller: wiki_controllers/steam/controllers-steamdeck.md
    - Steam - Steam Controller: wiki_controllers/steam/controllers-steam.md

  - Controllers - Generic - Standard Type (WIP):
    - Generic Standard - RetroDECK Hotkeys: wiki_controllers/generic/standard/generic-standard-hotkeys.md
    - About Generic Standard: wiki_controllers/generic/standard/generic-standard.md

  - Controllers - Accessibility (WIP):
    - About Accessibility Controllers: wiki_controllers/accessibility/about-accessibility.md
    - Xbox Adaptive Controller: wiki_controllers/accessibility/xac.md

  - Controllers - Arcade (WIP):
    - About Arcade Controllers: wiki_controllers/arcade/about-arcade.md

  - Controllers - Flight (WIP):
    - About Flight Controllers: wiki_controllers/flight/about-flight.md

  - Controllers - Gimmick (WIP):
    - About Gimmick Controllers: wiki_controllers/gimmick/about-gimmick.md
    - Buzz - Buzzers: wiki_controllers/gimmick/buzz-buzzers.md
    - Cycling Sports - Cyberbike: wiki_controllers/gimmick/cyberbike.md
    - Densha de Go! - Shinkansen Cockpit: wiki_controllers/gimmick/shinkansen-cockpit.md
    - Drawsome! - Tablet: wiki_controllers/gimmick/drawsome-tablet.md
    - EA - Active Heart Rate Monitor: wiki_controllers/gimmick/active-heart-rate-monitor.md
    - SEGA - Seamic Controller: wiki_controllers/gimmick/sega-seamic.md
    - Steel Battalion  - Cockpit: wiki_controllers/gimmick/steel-battalion-cockpit.md
    - Tony Hawk RIDE - Balance Board: wiki_controllers/gimmick/ride-balance-board.md
    - Udraw - Tablet: wiki_controllers/gimmick/udraw-tablet.md

  - Controllers - (WIP):
    - Lightguns - Controllers (WIP): wiki_controllers/controllers-lightguns.md
    - Music / Rhythm - Controllers (WIP): wiki_controllers/controllers-music.md
    - Racing - Controllers (WIP): wiki_controllers/controllers-racing.md
    - Toys-to-life - Controllers (WIP): wiki_controllers/controllers-toys-to-life.md


